# Generated by Django 2.2 on 2020-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=True, help_text='biographie du joueur'),
            preserve_default=False,
        ),
    ]
