# Generated by Django 2.2 on 2020-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(default=True, help_text='Prénom du joueur', max_length=120),
            preserve_default=False,
        ),
    ]
